import { EventItem } from "@/lib/types";
import { placeholderImage } from "@/lib/images";

// Curated sample events used whenever the Wix Headless connection isn't
// configured (e.g. local preview without WIX_CLIENT_ID), so the site is
// always fully browsable out of the box.
export const mockEvents: EventItem[] = [
  {
    id: "evt-1",
    slug: "sunrise-circle-yoga",
    imageUrl: placeholderImage("sunrise-circle-yoga"),
    title: "Sunrise Circle Yoga & Journaling",
    category: "Wellness",
    tagline: "Start the week grounded, together.",
    description:
      "Join us for a gentle vinyasa flow followed by guided journaling as the sun comes up over the park. All levels welcome — mats and warm tea provided. This is a phone-free hour to breathe, stretch, and set intentions alongside women who get it.",
    startDate: "2026-07-14T06:30:00-04:00",
    endDate: "2026-07-14T08:00:00-04:00",
    locationName: "Riverside Meadow Pavilion",
    address: "220 Riverside Dr, Brooklyn, NY",
    isOnline: false,
    capacity: 30,
    spotsLeft: 6,
    featured: true,
    host: "Maya Chen",
    accent: "rose",
  },
  {
    id: "evt-2",
    slug: "founders-fireside-chat",
    imageUrl: placeholderImage("founders-fireside-chat"),
    title: "Founders' Fireside: Building Without Burning Out",
    category: "Professional",
    tagline: "Real talk from women who've built and rebuilt.",
    description:
      "A candid panel with three founders on fundraising, boundaries, and what nobody tells you about scaling a company while staying sane. Followed by small-group networking and a hosted wine hour.",
    startDate: "2026-07-17T18:30:00-04:00",
    endDate: "2026-07-17T20:30:00-04:00",
    locationName: "The Hearth Coworking Loft",
    address: "88 Bond St, Brooklyn, NY",
    isOnline: false,
    capacity: 60,
    spotsLeft: 14,
    featured: true,
    host: "Priya Anand",
    accent: "plum",
  },
  {
    id: "evt-3",
    slug: "trailblazers-hike",
    imageUrl: placeholderImage("trailblazers-hike"),
    title: "Trailblazers Sunday Hike",
    category: "Outdoors",
    tagline: "Fresh air, good company, no pressure.",
    description:
      "A moderate 5-mile loop through the ridge trail, paced for conversation over speed. We regroup at every overlook, so no one hikes alone. Bring water, layers, and snacks to share at the summit picnic.",
    startDate: "2026-07-19T09:00:00-04:00",
    endDate: "2026-07-19T12:30:00-04:00",
    locationName: "Bear Ridge Trailhead",
    address: "Bear Mountain State Park, NY",
    isOnline: false,
    capacity: 20,
    spotsLeft: 3,
    featured: true,
    host: "Jo Whitfield",
    accent: "gold",
  },
  {
    id: "evt-4",
    slug: "paint-and-pour-studio-night",
    imageUrl: placeholderImage("paint-and-pour-studio-night"),
    title: "Paint & Pour Studio Night",
    category: "Creative",
    tagline: "No talent required, just good playlists.",
    description:
      "An unhurried evening of guided acrylic painting, playlist requests, and a little wine. Every canvas goes home with you — and no two ever look the same, which is the whole point.",
    startDate: "2026-07-22T19:00:00-04:00",
    endDate: "2026-07-22T21:00:00-04:00",
    locationName: "Lumen Art Studio",
    address: "45 Vine St, Brooklyn, NY",
    isOnline: false,
    capacity: 24,
    spotsLeft: 9,
    featured: false,
    host: "Renata Silva",
    accent: "rose",
  },
  {
    id: "evt-5",
    slug: "book-club-untamed",
    imageUrl: placeholderImage("book-club-untamed"),
    title: "Book Club: Chapters 1–9",
    category: "Social",
    tagline: "This month's pick, and the tea that comes with it.",
    description:
      "A cozy monthly gathering for open, unfiltered discussion — no need to have finished the book. Tea and snacks provided; bring your dog-eared copy and your honest opinions.",
    startDate: "2026-07-24T18:00:00-04:00",
    endDate: "2026-07-24T19:30:00-04:00",
    locationName: "The Reading Room",
    address: "12 Vale St, Brooklyn, NY",
    isOnline: false,
    capacity: 18,
    spotsLeft: 5,
    featured: false,
    host: "Community Team",
    accent: "plum",
  },
  {
    id: "evt-6",
    slug: "virtual-negotiation-workshop",
    imageUrl: placeholderImage("virtual-negotiation-workshop"),
    title: "Ask With Confidence: A Negotiation Workshop",
    category: "Professional",
    tagline: "Practice the ask before you need it.",
    description:
      "A live virtual workshop on negotiating salary, scope, and self-worth — with breakout role-play so you leave having actually practiced the conversation, not just heard about it.",
    startDate: "2026-07-29T12:00:00-04:00",
    endDate: "2026-07-29T13:30:00-04:00",
    locationName: "Online via Zoom",
    address: "Link sent after RSVP",
    isOnline: true,
    capacity: 100,
    spotsLeft: 41,
    featured: false,
    host: "Dana Okafor",
    accent: "gold",
  },
  {
    id: "evt-7",
    slug: "new-in-town-mixer",
    imageUrl: placeholderImage("new-in-town-mixer"),
    title: "New in Town Mixer",
    category: "Social",
    tagline: "For anyone who just moved and misses their people.",
    description:
      "Low-key mixer designed for easy conversation — name tags, icebreaker cards, and a host circulating to make sure nobody's stuck alone. Come as you are, leave with plans for next week.",
    startDate: "2026-08-02T18:30:00-04:00",
    endDate: "2026-08-02T21:00:00-04:00",
    locationName: "Golden Hour Rooftop Bar",
    address: "310 Bedford Ave, Brooklyn, NY",
    isOnline: false,
    capacity: 80,
    spotsLeft: 22,
    featured: true,
    host: "Community Team",
    accent: "rose",
  },
  {
    id: "evt-8",
    slug: "morning-run-club",
    imageUrl: placeholderImage("morning-run-club"),
    title: "Morning Run Club: 5K Fun Run",
    category: "Outdoors",
    tagline: "All paces welcome, coffee guaranteed.",
    description:
      "A friendly 5K loop through the park with pace groups so nobody's left behind. We finish together for iced coffee and pastries. Strollers and dogs welcome on the back half of the group.",
    startDate: "2026-08-05T07:00:00-04:00",
    endDate: "2026-08-05T08:15:00-04:00",
    locationName: "Prospect Park Loop, West Entrance",
    address: "Prospect Park, Brooklyn, NY",
    isOnline: false,
    capacity: 40,
    spotsLeft: 17,
    featured: false,
    host: "Jo Whitfield",
    accent: "gold",
  },
];

export function getMockEventBySlug(slug: string): EventItem | undefined {
  return mockEvents.find((e) => e.slug === slug);
}
